alias ls="ls --color=auto"
alias l="ls"
alias la="ls -a --color=auto"
alias lla="ls -al --color=auto"
alias lal="ls -al --color=auto"
alias cdd="cd ../"
alias cddd="cd ../../"
alias cdddd="cd ../../../"
alias c="clear"
alias cs="coding-style ./ ./"
alias mc="mr_clean"
alias please="sudo"
alias pt="push_that.sh"
alias ,,,="setxkbmap us"
alias ga="git add"
alias gaa="echo \"check objects files\" ; git add --all"
alias gc="git commit -m"
alias gp="git push"
alias gst="git status"
alias bc="bc -l"
alias diff="colordiff"
alias i3lock="i3lock -c 1c79bd"
alias vim="nvim"
alias lucas="echo \"c koi MUL\""
alias ana="echo \"<3\""
